"""
LegalX AI Knowledge Centre - FastAPI Backend
Main application entry point.
"""

import asyncio
import logging
import os
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

from pipeline.run_pipeline import run_full_pipeline, load_all_cards, load_card, process_topic
from pipeline.processor import answer_question, answer_question_no_rag
from pipeline.vector_store import retrieve_context, is_topic_indexed
from pipeline.audio import generate_audio, get_audio_path, audio_exists
from pipeline.scraper import get_all_topics, get_topic_metadata, scrape_legal_content

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

AUDIO_DIR = os.path.join(os.path.dirname(__file__), "audio")
os.makedirs(AUDIO_DIR, exist_ok=True)
os.makedirs(os.path.join(os.path.dirname(__file__), "data"), exist_ok=True)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Run the AI pipeline on startup (background task)."""
    logger.info("LegalX server starting — launching AI pipeline in background...")
    asyncio.create_task(run_full_pipeline(force=False))
    yield
    logger.info("LegalX server shutting down.")


app = FastAPI(
    title="LegalX AI Knowledge Centre API",
    description="AI-powered legal knowledge platform using Grok (xAI)",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000", "*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─────────────────────────────────────────────
# Request / Response Models
# ─────────────────────────────────────────────

class QuestionRequest(BaseModel):
    question: str

class RegenerateRequest(BaseModel):
    force: bool = True


# ─────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────

@app.get("/health")
async def health():
    """Health check endpoint."""
    api_key_set = bool(os.getenv("XAI_API_KEY", "").strip())
    return {
        "status": "ok",
        "api_key_configured": api_key_set,
        "message": "LegalX AI Knowledge Centre is running",
    }


@app.get("/api/topics")
async def get_topics():
    """Return all legal topic cards (generated by AI pipeline)."""
    cards = load_all_cards()
    all_topics = get_all_topics()

    result = []
    for topic in all_topics:
        key = topic["key"]
        card = cards.get(key, {})
        result.append({
            "key": key,
            "name": topic["name"],
            "full_name": topic["full_name"],
            "description": card.get("description", "Processing with AI... Please refresh shortly."),
            "processed": card.get("processed", False),
            "has_audio": card.get("has_audio", False),
        })
    return result


@app.get("/api/topics/{topic_key}")
async def get_topic(topic_key: str):
    """Return full card data for a specific topic."""
    card = load_card(topic_key)
    if not card:
        meta = get_topic_metadata(topic_key)
        if not meta:
            raise HTTPException(status_code=404, detail=f"Topic '{topic_key}' not found")
        return {
            "key": topic_key,
            "name": meta["name"],
            "full_name": meta["full_name"],
            "description": "AI is processing this topic... Please refresh in a moment.",
            "summary": None,
            "key_info": None,
            "has_audio": False,
            "processed": False,
        }
    return card


@app.post("/api/topics/{topic_key}/regenerate")
async def regenerate_topic(topic_key: str, background_tasks: BackgroundTasks):
    """Trigger re-processing of a topic through the AI pipeline."""
    meta = get_topic_metadata(topic_key)
    if not meta:
        raise HTTPException(status_code=404, detail=f"Topic '{topic_key}' not found")

    background_tasks.add_task(process_topic, topic_key, meta["name"], force=True)
    return {"message": f"Re-processing '{meta['name']}' in background. Refresh in ~30 seconds."}


@app.post("/api/topics/{topic_key}/ask")
async def ask_question_endpoint(topic_key: str, body: QuestionRequest):
    """
    Answer a legal question using RAG (ChromaDB retrieval + Grok generation).
    Falls back to direct LLM if vector store not indexed.
    """
    card = load_card(topic_key)
    topic_name = card["name"] if card else topic_key

    question = body.question.strip()
    if not question:
        raise HTTPException(status_code=400, detail="Question cannot be empty")

    sources = []

    # Try RAG first
    if is_topic_indexed(topic_key):
        try:
            chunks = retrieve_context(topic_key, question, n_results=4)
            if chunks:
                context_texts = [c["text"] for c in chunks]
                sources = [
                    {"text": c["text"][:150] + "...", "source": c["source"], "score": c["score"]}
                    for c in chunks
                ]
                answer = answer_question(topic_name, question, context_texts)
                return {
                    "answer": answer,
                    "sources": sources,
                    "method": "RAG",
                }
        except Exception as e:
            logger.warning(f"RAG retrieval failed: {e}, falling back to direct LLM")

    # Fallback: Direct LLM with full legal text
    try:
        legal_text = await scrape_legal_content(topic_key)
        answer = answer_question_no_rag(topic_name, question, legal_text)
        return {
            "answer": answer,
            "sources": [],
            "method": "Direct LLM",
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to answer question: {str(e)}")


@app.get("/api/topics/{topic_key}/audio")
@app.head("/api/topics/{topic_key}/audio")
async def get_audio(topic_key: str):
    """Stream/download the audio summary for a topic."""
    path = get_audio_path(topic_key)
    if not path:
        # Try to generate it on demand
        card = load_card(topic_key)
        if not card or not card.get("summary"):
            raise HTTPException(status_code=404, detail="Audio not yet generated. Please wait for the pipeline to complete.")
        try:
            generate_audio(topic_key, card["summary"])
            path = get_audio_path(topic_key)
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Audio generation failed: {str(e)}")

    return FileResponse(
        path=path,
        media_type="audio/mpeg",
        filename=f"{topic_key}_summary.mp3",
        headers={"Content-Disposition": f'inline; filename="{topic_key}_summary.mp3"'},
    )


@app.post("/api/pipeline/run")
async def trigger_pipeline(background_tasks: BackgroundTasks, body: RegenerateRequest = RegenerateRequest()):
    """Manually trigger the full pipeline (admin endpoint)."""
    background_tasks.add_task(run_full_pipeline, body.force)
    return {"message": "Full pipeline triggered in background."}


@app.get("/api/pipeline/status")
async def pipeline_status():
    """Check the processing status of all topics."""
    cards = load_all_cards()
    all_topics = get_all_topics()
    status = []
    for topic in all_topics:
        key = topic["key"]
        card = cards.get(key, {})
        status.append({
            "key": key,
            "name": topic["name"],
            "processed": card.get("processed", False),
            "has_audio": card.get("has_audio", False),
            "chunk_count": card.get("chunk_count", 0),
        })
    return {"topics": status}
